### ISSUE TITLE
Contributing link broken

### ISSUE THREAD

**Issue by NonlinearFruit** [guipdutra/awesome-geek-podcasts#127]
The contributing link at the bottom of the README is broken.

**Comment by pamo** [comment]
I think the link is meant to be clicked on from http://guipdutra.github.io/awesome-geek-podcasts/ 
i.e. http://guipdutra.github.io/awesome-geek-podcasts/CONTRIBUTING.html
However, if you're contributing you'd most likely be clicking from the github project. Maybe better to stick to one but link to the full (rather than relative) url.
